jobs:
  - job: "CodeAnalysis"
    pool:
      vmImage: "windows-latest"
    displayName: "Code Analysis with SonarCloud"
    steps:
      # Restore NuGet Packages
      - script: 'dotnet restore "Kraken.WebSockets.sln"'
        displayName: "Restore NuGet Packages"

      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: "SonarCloud M4cX"
          organization: "m4cx-github"
          scannerMode: "MSBuild"
          projectKey: "kraken-wsapi-dotnet"
          projectName: "kraken-wsapi-dotnet"

      # Build all projects with specific version number
      - script: 'dotnet build "Kraken.WebSockets.sln" -c Release --no-restore'
        displayName: "dotnet build"
      # Execute defined tests and collect code coverage
      - task: DotNetCoreCLI@2
        displayName: "dotnet test"
        inputs:
          command: test
          projects: test/Kraken.WebSockets.Tests/Kraken.WebSockets.Tests.csproj
          arguments: '--no-restore --no-build -c Release --collect "Code coverage" --settings:./codecoverage.runsettings'
      - task: CopyFiles@2
        displayName: "Copy Files to staging"
        inputs:
          SourceFolder: "./build"
          TargetFolder: "$(Build.ArtifactStagingDirectory)"
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: drop"
        inputs:
          pathtoPublish: "$(Build.ArtifactStagingDirectory)"
          artifactName: "drop"
      - task: SonarCloudAnalyze@1

      - task: SonarCloudPublish@1
        inputs:
          pollingTimeoutSec: "300"
